### PR TITLE
Ability to Stop ThreadedRuntime

### PR DESCRIPTION
**Pull request by smashew**
Addresses issue where you cannot stop the threaded runtime. Also fixed issue with delayed tests running slowly and creating high number of threads.

### CODE REVIEW

**Comment by smashew** [comment]
:+1: This looks great! More tests!

**Comment by sieverssj** [comment]
:+1:

**Comment by sieverssj** [comment]
Internal build failed.  Come talk to me when you get a chance.

**Comment by smashew** [comment]
Build is passing.

**Comment by sieverssj** [comment]
:+1: again :)

**Pull request merged**
